name: CI build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=DefaultContainer

      - name: Test
        run: dotnet test

      - name: Docker Login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag built container
        uses: actions-hub/docker/cli@master
        with:
          args: tag literature-works-api:1.0.0 dedicated407/literature-works-api:latest

      - name: Push built container to Docker hub
        uses: actions-hub/docker/cli@master
        with:
          args: push dedicated407/literature-works-api:latest
